//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geohashing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geohashing.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report it.
        /// </summary>
        public static string AboutBugReportLink {
            get {
                return ResourceManager.GetString("AboutBugReportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send me an e-mail.
        /// </summary>
        public static string AboutEmailLink {
            get {
                return ResourceManager.GetString("AboutEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geohashing for Windows Phone, version %VERSION%, developed by Lucas Werkmeister..
        /// </summary>
        public static string AboutParagraph1 {
            get {
                return ResourceManager.GetString("AboutParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software, licensed under the GNU General Public License, version 3..
        /// </summary>
        public static string AboutParagraph2 {
            get {
                return ResourceManager.GetString("AboutParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view the source code %SOURCELINK%..
        /// </summary>
        public static string AboutParagraph3 {
            get {
                return ResourceManager.GetString("AboutParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a bug? %BUGREPORTLINK%! Or just %EMAILLINK%..
        /// </summary>
        public static string AboutParagraph4 {
            get {
                return ResourceManager.GetString("AboutParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string AboutSourceLink {
            get {
                return ResourceManager.GetString("AboutSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geohashing.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-zoom.
        /// </summary>
        public static string AutoZoomText {
            get {
                return ResourceManager.GetString("AutoZoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load hash.
        /// </summary>
        public static string CantLoadHashPrefix {
            get {
                return ResourceManager.GetString("CantLoadHashPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch location.
        /// </summary>
        public static string CantLocateText {
            get {
                return ResourceManager.GetString("CantLocateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal (1.034).
        /// </summary>
        public static string CoordinatesDisplayDecimal {
            get {
                return ResourceManager.GetString("CoordinatesDisplayDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMS (1°2&apos;3&apos;&apos;).
        /// </summary>
        public static string CoordinatesDisplayDegreeMinutesSeconds {
            get {
                return ResourceManager.GetString("CoordinatesDisplayDegreeMinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates mode.
        /// </summary>
        public static string CoordinatesModeText {
            get {
                return ResourceManager.GetString("CoordinatesModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJIA buffer size.
        /// </summary>
        public static string DjiaBufferSizeText {
            get {
                return ResourceManager.GetString("DjiaBufferSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentGraticule.
        /// </summary>
        public static string GeohashModeCurrentGraticule {
            get {
                return ResourceManager.GetString("GeohashModeCurrentGraticule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        public static string GeohashModeNearest {
            get {
                return ResourceManager.GetString("GeohashModeNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geohash mode.
        /// </summary>
        public static string GeohashModeText {
            get {
                return ResourceManager.GetString("GeohashModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default precision.
        /// </summary>
        public static string GeoPrecisionDefault {
            get {
                return ResourceManager.GetString("GeoPrecisionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string GeoPrecisionDisabled {
            get {
                return ResourceManager.GetString("GeoPrecisionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High precision.
        /// </summary>
        public static string GeoPrecisionHigh {
            get {
                return ResourceManager.GetString("GeoPrecisionHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting location....
        /// </summary>
        public static string GettingLocationText {
            get {
                return ResourceManager.GetString("GettingLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only load tile images over WiFi.
        /// </summary>
        public static string ImagesOverWifiText {
            get {
                return ResourceManager.GetString("ImagesOverWifiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length units.
        /// </summary>
        public static string LengthUnitsText {
            get {
                return ResourceManager.GetString("LengthUnitsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading hash....
        /// </summary>
        public static string LoadingHashText {
            get {
                return ResourceManager.GetString("LoadingHashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate on app start.
        /// </summary>
        public static string LocateOnAppStartText {
            get {
                return ResourceManager.GetString("LocateOnAppStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current hash.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerial.
        /// </summary>
        public static string MapCartographicModeAerial {
            get {
                return ResourceManager.GetString("MapCartographicModeAerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string MapCartographicModeHybrid {
            get {
                return ResourceManager.GetString("MapCartographicModeHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string MapCartographicModeRoad {
            get {
                return ResourceManager.GetString("MapCartographicModeRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string MapCartographicModeTerrain {
            get {
                return ResourceManager.GetString("MapCartographicModeTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map mode.
        /// </summary>
        public static string MapModeText {
            get {
                return ResourceManager.GetString("MapModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geohash for yyyy-MM-dd, %LAT%, %LON%.
        /// </summary>
        public static string MapsAppLabel {
            get {
                return ResourceManager.GetString("MapsAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJIA not available.
        /// </summary>
        public static string NoDjiaSuffix {
            get {
                return ResourceManager.GetString("NoDjiaSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string NoInternetSuffix {
            get {
                return ResourceManager.GetString("NoInternetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open in Maps.
        /// </summary>
        public static string OpenInMapsButtonText {
            get {
                return ResourceManager.GetString("OpenInMapsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start screen.
        /// </summary>
        public static string PinStartScreenButtonText {
            get {
                return ResourceManager.GetString("PinStartScreenButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing live tile....
        /// </summary>
        public static string PreparingTileText {
            get {
                return ResourceManager.GetString("PreparingTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location information is used only locally and not sent to anyone over the internet. Other potentially sensitive data is not used. No one, not even us, has access to your sensitive data over this app..
        /// </summary>
        public static string PrivacyPolicyParagraph1 {
            get {
                return ResourceManager.GetString("PrivacyPolicyParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We respect your privacy; should we, by some means, receive sensitive data from you, we will handle them confidentially and not pass them on to third parties..
        /// </summary>
        public static string PrivacyPolicyParagraph2 {
            get {
                return ResourceManager.GetString("PrivacyPolicyParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reload location.
        /// </summary>
        public static string ReloadLocationButtonText {
            get {
                return ResourceManager.GetString("ReloadLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings &amp; about.
        /// </summary>
        public static string SettingsAboutButtonText {
            get {
                return ResourceManager.GetString("SettingsAboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        public static string UnitSystemImperial {
            get {
                return ResourceManager.GetString("UnitSystemImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string UnitSystemMetric {
            get {
                return ResourceManager.GetString("UnitSystemMetric", resourceCulture);
            }
        }
    }
}
